cli: expose OPAs entrypoints, except for 'run'
With this, `load` will have the same entrypoints as the OPA CLI, except for
`run`, which is skipped:

    $ go run main.go --help
    Styra Load

    Usage:
      main [command]

    Available Commands:
      bench        Benchmark a Rego query
      build        Build an OPA bundle
      capabilities Print the capabilities of OPA
      check        Check Rego source files
      completion   Generate the autocompletion script for the specified shell
      deps         Analyze Rego query dependencies
      eval         Evaluate a Rego query
      exec         Execute against input files
      fmt          Format Rego source files
      help         Help about any command
      inspect      Inspect OPA bundle(s)
      parse        Parse Rego source file
      sign         Generate an OPA bundle signature
      test         Execute Rego test cases
      version      Print the version of OPA

    Flags:
      -h, --help   help for main

    Use "main [command] --help" for more information about a command.

    $ go run main.go eval -fpretty '1+1'
    2

    $ go run main.go version
    Version: 0.45.0-dev
    Build Commit:
    Build Timestamp:
    Build Hostname:
    Go Version: go1.19
    Platform: darwin/amd64
    WebAssembly: unavailable

    $ go run main.go run
    Error: unknown command "run" for "main"
    Run 'main --help' for usage.
    unknown command "run" for "main"
    exit status 1

The binary is called main here because we haven't hardcoded a name.

Signed-off-by: Stephan Renatus <stephan@styra.com>